# * Power Analysis Configuration
# * Version: Dev
params:
  max_cores: # ! ADJUST AS NEEDED; default (i.e., NULL) is conserved at 4 cores
  n_lvl1: [3]
  n_lvl2: [100, 200, 300]
  lvl1_effect_std: [0.30]
  lvl2_effect_std: [0.30]
  xlvl_effect_std: [0.30]
  icc: [0.30]
  rand_slope_std: [0.09]
  alpha: [0.05]
  use_REML: [TRUE]
  n_sims: 10 # ! ADJUST AS NEEDED; LOWER FOR DEV PURPOSES; 1K IS RECOMMENDED
  verbose: FALSE
  return_df: TRUE
  rand_seed: 1879
